Homework-30
Otus-DevOps-2017-11/rastamalik_microservices pull request #15
Opened 2018-04-06 11:36 UTC by rastamalik

Выполнено ДЗ-30

2018-05-02 16:59 UTC, vitkhab requested changes
С текущей конфигурацией, приложение не работает. Надо бы починить.

Для приемки ДЗ нужно:
- починить сетевую политику mongodb
- починить описание ui-сервиса
- починить PersistentVolumeClaim для монги

Я понимаю, задание было сделано давно. Вспомнить будет сложно, я готов помочь. Будут вопросы - обращайся.

2018-05-02 16:59 UTC, vitkhab commented on kubernetes/kube/mongo-network-policy.yml
> +          component: post
Неправильно применение правил сетевой политики. Для того, чтобы политика сработала, нужно чтобы исполнялись все правила после `matchLabels`, то есть трафик разрешен только для подов со всеми Label'ами  app=reddit, component=comment и component=post. В конфигурации нет таких подов.

Есть два варианта:
- Правила в рамках `from` отрабатываются до первог совпадения (работают так, если бы между ними стояла операция логического ИЛИ)
- Правила в рамках `ingress` отрабатываются до первог совпадения (работают так, если бы между ними стояла операция логического ИЛИ)

2018-05-02 16:59 UTC, vitkhab commented on kubernetes/kube/ui-service.yml
> +  type: LoadBalancer
Неправильно выбранный тип сервиса. Описанная в PR конфигурация создает нерабочий `ingress` и не нужный (по заданию) балансировщик.
Сделай, пожалуйста, так, чтобы работал `ingress`

2018-05-02 16:59 UTC, vitkhab commented on kubernetes/kube/ui-service.yml
> +    port: 80
Эту строчку тоже придется заменить. Указанный порт не соответствует настройкам ингресса

2018-05-02 16:59 UTC, vitkhab commented on kubernetes/kube/mongo-claim-dynamic.yml
> +  storageClassName: slow
В конфигурации не описан `storageClassName` с именем "slow". Зато описан другой класс.

В гисте была опечатка в этом месте. Тем не менее на слайдах презинтации - все указано правильно.

2018-05-03 06:11 UTC, rastamalik commented
Привет, поправил.

2018-05-03 06:11 UTC, rastamalik commented
Привет, поправил.

2 мая 2018 г., 19:59 пользователь Vitaly Khabarov <notifications@github.com>
написал:

> *@vitkhab* requested changes on this pull request.
>
> С текущей конфигурацией, приложение не работает. Надо бы починить.
>
> Для приемки ДЗ нужно:
>
>    - починить сетевую политику mongodb
>    - починить описание ui-сервиса
>    - починить PersistentVolumeClaim для монги
>
> Я понимаю, задание было сделано давно. Вспомнить будет сложно, я готов
> помочь. Будут вопросы - обращайся.
> ------------------------------
>
> In kubernetes/kube/mongo-network-policy.yml
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#discussion_r185531116>
> :
>
> > +  labels:
> +    app: reddit
> +spec:
> +  podSelector:
> +    matchLabels:
> +      app: reddit
> +      component: mongo
> +  policyTypes:
> +  - Ingress
> +  ingress:
> +  - from:
> +    - podSelector:
> +        matchLabels:
> +          app: reddit
> +          component: comment
> +          component: post
>
> Неправильно применение правил сетевой политики. Для того, чтобы политика
> сработала, нужно чтобы исполнялись все правила после matchLabels, то есть
> трафик разрешен только для подов со всеми Label'ами app=reddit,
> component=comment и component=post. В конфигурации нет таких подов.
>
> Есть два варианта:
>
>    - Правила в рамках from отрабатываются до первог совпадения (работают
>    так, если бы между ними стояла операция логического ИЛИ)
>    - Правила в рамках ingress отрабатываются до первог совпадения
>    (работают так, если бы между ними стояла операция логического ИЛИ)
>
> ------------------------------
>
> In kubernetes/kube/ui-service.yml
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#discussion_r185531681>
> :
>
> > @@ -0,0 +1,18 @@
> +---
> +apiVersion: v1
> +kind: Service
> +metadata:
> +  name: ui
> +  labels:
> +    app: reddit
> +    component: ui
> +spec:
> +  type: LoadBalancer
>
> Неправильно выбранный тип сервиса. Описанная в PR конфигурация создает
> нерабочий ingress и не нужный (по заданию) балансировщик.
> Сделай, пожалуйста, так, чтобы работал ingress
> ------------------------------
>
> In kubernetes/kube/ui-service.yml
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#discussion_r185553149>
> :
>
> > @@ -0,0 +1,18 @@
> +---
> +apiVersion: v1
> +kind: Service
> +metadata:
> +  name: ui
> +  labels:
> +    app: reddit
> +    component: ui
> +spec:
> +  type: LoadBalancer
> +  ports:
> +  - nodePort: 32092
> +    port: 80
>
> Эту строчку тоже придется заменить. Указанный порт не соответствует
> настройкам ингресса
> ------------------------------
>
> In kubernetes/kube/mongo-claim-dynamic.yml
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#discussion_r185556938>
> :
>
> > @@ -0,0 +1,12 @@
> +---
> +kind: PersistentVolumeClaim
> +apiVersion: v1
> +metadata:
> +  name: mongo-pvc-dynamic
> +spec:
> +  accessModes:
> +    - ReadWriteOnce
> +  storageClassName: slow
>
> В конфигурации не описан storageClassName с именем "slow". Зато описан
> другой класс.
>
> В гисте была опечатка в этом месте. Тем не менее на слайдах презинтации -
> все указано правильно.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#pullrequestreview-116938597>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsH6GuBkORZgmiAvPAv9O_kC6_IoLks5tueXZgaJpZM4TJ6Z_>
> .
>

2018-05-03 06:12 UTC, vitkhab requested changes
Молодец! Исправил все что я просил, и привнес одну небольшой опечатку в конфигурацию. Прошу ее исправить

2018-05-03 06:12 UTC, vitkhab commented on kubernetes/kube/ui-service.yml
> +    port: 9292
поменяй `port: 9292` на `- port: 9292`, иначе конфигурация не валидна

2018-05-03 06:14 UTC, rastamalik commented
Поправил

2018-05-03 9:12 GMT+03:00 Vitaly Khabarov <notifications@github.com>:

> *@vitkhab* requested changes on this pull request.
>
> Исправил все что я просил, и привнес одну небольшой опечатку в
> конфигурацию. Прошу ее исправить
> ------------------------------
>
> In kubernetes/kube/ui-service.yml
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#discussion_r185703178>
> :
>
> > @@ -9,8 +9,7 @@ metadata:
>  spec:
>    type: LoadBalancer
>    ports:
> -  - nodePort: 32092
> -    port: 80
> +    port: 9292
>
> поменяй port: 9292 на - port: 9292, иначе конфигурация не валидна
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/15#pullrequestreview-117144282>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsDLHPQRBroQHHF4yr0PrzaP9YnTCks5tup_AgaJpZM4TJ6Z_>
> .
>

2018-05-03 06:28 UTC, vitkhab approved these changes
Спасибо! Можно мерджить

2018-05-22 12:28 UTC, merged