Homework-16
Otus-DevOps-2017-11/rastamalik_microservices pull request #3
Opened 2018-02-06 08:46 UTC by rastamalik

Выполнено ДЗ-16

2018-02-07 09:26 UTC, serjs requested changes
Привет!

Добавь в alpine пакет ruby-json. Т.к.  он по дефолту идет в ubuntu ruby пакете, а у нас его нет в Gemfile. Также можно добавить его в Gemfile, на выбор. В остальном базово все сделано и будет работать.

2018-02-07 12:46 UTC, rastamalik commented
Поправил

7 февраля 2018 г., 12:26 пользователь Sergey Bogatyrets <
notifications@github.com> написал:

> *@serjs* requested changes on this pull request.
>
> Привет!
>
> Добавь в alpine пакет ruby-json. Т.к. он по дефолту идет в ubuntu ruby
> пакете, а у нас его нет в Gemfile. Также можно добавить его в Gemfile, на
> выбор. В остальном базово все сделано и будет работать.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/3#pullrequestreview-94638800>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsC9xKeMTdN58KJRJmONF3beyEQgOks5tSWw_gaJpZM4R6r4P>
> .
>

2018-02-11 13:05 UTC, serjs approved these changes

2018-02-11 13:06 UTC, serjs commented
Ок, можно мержить

2018-02-12 06:02 UTC, merged