Homework-21
Otus-DevOps-2017-11/rastamalik_microservices pull request #7
Opened 2018-02-26 08:33 UTC by rastamalik

Выполнено ДЗ-21

2018-02-28 09:06 UTC, Nklya requested changes
Ревью после мержа предыдущего PR

2018-03-03 17:10 UTC, Nklya requested changes
Добрый вечер.

Александр, в PR должно быть отражено то, что выполнено в ДЗ.

С чего вдруг здесь появляются заново все файлы в /src?

Если ты выполняешь сразу несколько ДЗ, то после сдачи предыдущего нужно подмерживать мастер в ветку, чтобы актуализировать состояние.

Нужно:
1. Подмержить мастер в эту ветку, чтобы  изменения стали нормальные.
2. Вычистить дичь из .gitignore. У тебя нет папки `terraform-gitlab`
3. Вычитить .env
4. Вычистить docker-compose.yml.save
5. Проверить ридми и исправить его и композ файлы. У тебя нет mongodb_exporter нигде.


После фикса всего этого повторное ревью будет.

2018-03-03 17:10 UTC, Nklya commented on .gitignore
> +terraform-gitlab/terraform.tfvars
И где у тебя в репозитории есть папка `terraform-gitlab`, что ее нужно было добавить в .gitignore?

2018-03-03 17:10 UTC, Nklya commented on README.md
> +14. Создание мониторинга **MongoDB**. Я использовал mongo-exporter-**dcu/mongodb-exporter**. В папку **monitoring** клонировал **dcu/mongodb-exporter**, создал образ **mongodb-exporter** ```docker bu
Интересно, где же он, если у тебя его нет ни в репозтории, ни на докер хабе?

2018-03-03 17:10 UTC, Nklya commented on docker/.env
> +
.env должен быть в .gitgnore и вычищен из репы

2018-03-03 17:10 UTC, Nklya commented on docker/docker-compose.yml.save
> +version: '3.3'
Этот файл здесь зачем?

2018-03-05 06:46 UTC, rastamalik commented
Привет, вроде поправил, про папку src не понял.

3 марта 2018 г., 20:10 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
> Добрый вечер.
>
> Александр, в PR должно быть отражено то, что выполнено в ДЗ.
>
> С чего вдруг здесь появляются заново все файлы в /src?
>
> Если ты выполняешь сразу несколько ДЗ, то после сдачи предыдущего нужно
> подмерживать мастер в ветку, чтобы актуализировать состояние.
>
> Нужно:
>
>    1. Подмержить мастер в эту ветку, чтобы изменения стали нормальные.
>    2. Вычистить дичь из .gitignore. У тебя нет папки terraform-gitlab
>    3. Вычитить .env
>    4. Вычистить docker-compose.yml.save
>    5. Проверить ридми и исправить его и композ файлы. У тебя нет
>    mongodb_exporter нигде.
>
> После фикса всего этого повторное ревью будет.
> ------------------------------
>
> In .gitignore
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/7#discussion_r172022134>
> :
>
> > @@ -0,0 +1,19 @@
> +gh-md-toc
> +reddit-microservices/.env
> +terraform-gitlab/terraform.tfvars
>
> И где у тебя в репозитории есть папка terraform-gitlab, что ее нужно было
> добавить в .gitignore?
> ------------------------------
>
> In README.md
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/7#discussion_r172022247>
> :
>
> > +      - /:/rootfs:ro
> +    command:
> +      - '--path.procfs=/host/proc'
> +      - '--path.sysfs=/host/sys'
> +- '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
> +```
> +13. И добавим **job** в **prometheus.yml**:
> +```
> +scrape_configs:
> +...
> +- job_name: 'node'
> +static_configs:
> +- targets:
> +- 'node-exporter:9100'
> +```
> +14. Создание мониторинга **MongoDB**. Я использовал mongo-exporter-**dcu/mongodb-exporter**. В папку **monitoring** клонировал **dcu/mongodb-exporter**, создал образ **mongodb-exporter** ```docker build -t mongodb_exporter .```. В **prometheus.yml** добавил **job**:
>
> Интересно, где же он, если у тебя его нет ни в репозтории, ни на докер
> хабе?
> ------------------------------
>
> In docker/.env
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/7#discussion_r172022308>
> :
>
> > @@ -0,0 +1,4 @@
> +
>
> .env должен быть в .gitgnore и вычищен из репы
> ------------------------------
>
> In docker/docker-compose.yml.save
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/7#discussion_r172022324>
> :
>
> > @@ -0,0 +1,74 @@
> +version: '3.3'
>
> Этот файл здесь зачем?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_microservices/pull/7#pullrequestreview-100980330>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsHTWZmcPH1qlL1Ce6srPdH_R4Ylyks5tas6dgaJpZM4SS2Iu>
> .
>

2018-03-07 20:26 UTC, Nklya requested changes
И откуда в этом PR вдруг появилась графана, при этом сделанная еще и не так, как в 23 ДЗ?

У тебя сейчас дифф 126 файлов. Как это вообще может быть интересно?

Приведи коммиты в нормальное состояние, чтобы этом PR были только те изменения, которые сделаны в этом ДЗ.

2018-03-12 09:17 UTC, closed without merging